### ISSUE TITLE
NTR: Request for S20 instrument (BODCNVS-368)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S20#1]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>instrument <p><b>Definition</b><p> A physical object that is a tool, an implement or a sampling/measuring device.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/49<p>

**Comment by bodcmahe** [comment]
Revised proposed definition: The reference is a physical object that is a tool, an implement or a sampling/measuring device

**Comment by bodcmahe** [comment]
Term published:

http://vocab.nerc.ac.uk/collection/S20/current/S2000025/
