### ISSUE TITLE
NTR: Request for S20 instrument and True North (BODCNVS-368)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S20#2]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>instrument and True North <p><b>Definition</b><p> The entity is defined relative to the instrument (e.g. a radar) and True North for direction<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/49<p>

**Comment by bodcmahe** [comment]
Term published:

http://vocab.nerc.ac.uk/collection/S20/current/S2000026/
